### ISSUE TITLE
FireFox ver

### ISSUE THREAD

**Issue by ThatOneCalculator** [robinuniverse/TwitFix-Extension#1]
:trollface:

**Comment by daisyUniverse** [comment]
![image](https://user-images.githubusercontent.com/12601774/149731452-19a593ef-d3b3-48c0-b66f-7c98deb5946c.png)
:sunglasses:

**Comment by ThatOneCalculator** [comment]
:egg: i love it pls ping when added

**Comment by DorukSega** [comment]
> 🥚 i love it pls ping when added

@ThatOneCalculator https://addons.mozilla.org/en-US/firefox/addon/twitfix-extension/

**Comment by ThatOneCalculator** [comment]
literally pissing my pants rn tysm
