### ISSUE TITLE
Bug on context menu

### ISSUE THREAD

**Issue by DorukSega** [robinuniverse/TwitFix-Extension#2]
Context menu stopped closing after an item is clicked, only tested on Chrome
Probably the element that is destroyed can't be reached anymore

**Comment by KawaiiTemDev** [comment]
Bump. still broken

**Comment by DorukSega** [comment]
After a bit of investigation,
this issue seems to be persistent even with the extension disabled so I don't know what to do.
I will try to see if I can make a hack around but from initial tries, I can say that it might have to stay as it is.

**Comment by DorukSega** [comment]
k I thought a bit about it and found a hack. 
```js
opt1.addEventListener("click",
    () => {
        navigator.clipboard.writeText(url.replace("https://", "https://fx"));
        document.body.click(); // hack here
    }
);
```
I trigger a click event at the document body right after picking an option, which hides the context menu.
